language: ruby
sudo: false

notifications:
  email: false

script:
  - (cd spec/dummy && bundle exec rake db:setup)
  - bundle exec rspec

matrix:
  include:
    - rvm: 2.3.3
      gemfile:
        - Gemfile-rails-4.0.x
        - Gemfile-rails-4.1.x
        - Gemfile-rails-4.2.x
    - rvm: 2.5.3
      gemfile:
        - Gemfile-rails-5.0.x
        - Gemfile-rails-5.1.x
        - Gemfile-rails-5.2.x
        - Gemfile-rails-6.0.x
